activation: relu
aug_scale: false
batch_size: 8
dataset: ./data/10kh5py.h5;./data/20kh5py.h5;./data/30kh5py.h5;./data/40kh5py.h5;./data/50kh5py.h5
debug: false
gpool_mlp: false
knn: 8,16,24
learning_rate: 0.0005
loss_ds: cd
loss_rec: unsupervised
min_lr: 1.0e-05
n_gpu: 1
net: DenoiseNet
no_prefilter: false
noise: 0.02
noise_high: 0.06
random_mesh: false
random_pool: false
sched_factor: 0.5
sched_patience: 10
seed: 2020
static_graph: false
subset_size: 7000
valdata: ./data/patches_20k_1024.h5;./data/patches_10k_1024.h5;./data/patches_30k_1024.h5;./data/patches_50k_1024.h5;./data/patches_80k_1024.h5
